kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
  namespace: <your-namespace>
data:
  grafana.ini: |
    [database] 
    type = postgres
    host = <ip>:5001 
    name = grafana
    user = grafana_user
    password = <grafana_user_pass> 

    [auth.ldap]
    enabled = true
    config_file = /etc/grafana/ldap.toml
    allow_sign_up = true
    skip_org_role_sync = true