kind: ConfigMap
apiVersion: v1
metadata:
  name: grana-ldap-config
  namespace: <your-namespace>
data:
  ldap.toml: |
    [[servers]] 
    host = "your-ldap-server" 
    port = 389 
    use_ssl = false 
    start_tls = false 
    ssl_skip_verify = true 
    bind_dn = "<your-domain>\\%s"
    search_filter = "(sAMAccountName=%s)" 
    search_base_dns = ["dc=<your-parameter>,dc=<your-parameter>,dc=ru"]

    [servers.attributes] 
    name = "givenName" 
    surname = "sn"  
    username = "sAMAccountName"  
    member_of = "memberOf"  
    email = "mail"